### ISSUE TITLE
Member Leave Embed

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#101]
When `guildMemberRemove` is triggered, an embed should be sent in the channel `LOG_CHANNEL_ID` that sends an embed stating:
- How long the member was in the guild (years, days, hours, minutes and seconds)
- If the user was authenticated (they will have the role `MEMBER_ROLE` if so)

I am not sure if you can get the roles a user had from the quit event, so may need some investigation.

**Comment by theboxmage** [comment]
Working on this, code is done minus one refactor needed. Having issues with tests, atm will finish asap
