### ISSUE TITLE
Inconsistency in test case naming

### ISSUE THREAD

**Issue by ajsaraujo** [codesupport/discord-bot#110]
Some test cases have a `::` prefix, while others don't.

![image](https://user-images.githubusercontent.com/34658414/92782242-2f669380-f37b-11ea-941f-083c74744156.png)

**Comment by LamboCreeper** [comment]
The prefix `::` indicates a `static` method, I believe these are all `static`.

**Comment by ajsaraujo** [comment]
Oops, didn't know that. My bad.
