### ISSUE TITLE
Add a development script

### ISSUE THREAD

**Issue by ajsaraujo** [codesupport/discord-bot#111]
To run the bot in development we first have to transpile to JavaScript. It would be nice if we had a `dev` script that used [ts-node](https://www.npmjs.com/package/ts-node) to transpile and run on the fly, such as `"dev": "ts-node src/app.ts"`.

**Comment by shyguy2601** [comment]
I'll do it

**Comment by shyguy2601** [comment]
can someone reassign me :/
