### ISSUE TITLE
Add a commands command

### ISSUE THREAD

**Issue by ajsaraujo** [codesupport/discord-bot#115]
It's not clear for newcomers how the bot is used - right now, the learning curve consists basically in watching other people use it. It would be nice if we had a `?commands` command that shows what are the available commands and what each one of them does. 

The command should loop over all the commands, getting their names, descriptions and aliases (if there are any) and finally showing this data on an embed.

A `help` alias would also fit nicely.

**Comment by LamboCreeper** [comment]
Thanks for the suggestion, however, this will no longer be needed with the introduction of the Interactions API.
