### ISSUE TITLE
Ghost ping detection triggers even if the user only mentions themselves

### ISSUE THREAD

**Issue by MatthaisUK** [codesupport/discord-bot#119]
See below for an example, where he mentioned himself, then later deleted the post.

![image](https://user-images.githubusercontent.com/45258725/96733956-ef4ef380-13b1-11eb-8053-ad1f86c68273.png)

**Comment by BlackBearFTW** [comment]
This issue should be assigned to me 👍 
I just need to integrate Lambo's mock package for testing and then this issue is fixed

**Comment by shyguy2601** [comment]
Just add an If statement for detecting if the mentioned user was the author of the original message?

**Comment by BlackBearFTW** [comment]
@shyguy2601 this issue is already done, look at the pull request I made

**Comment by shyguy2601** [comment]
Oh I did it too... 
0_0
well at least I think so

**Comment by shyguy2601** [comment]
well this is a bruh moment

**Comment by LamboCreeper** [comment]
Closing since this was resolved in #129.
