### ISSUE TITLE
Member Inspect Command 

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#130]
**As a** moderator
**I want to** be able to easily gather information about a user
**So that I** can fill out the member report form quicker

--- 

**Command Usage:** `?inspect <username | discord id>`
**Executeable by:** Everyone
**Executeable in:** #bot-chat

Returns an embed with the following fields:
- ID
- Username + Discriminator (formatted as Username#Discriminator)
- Joined Date + Time
- Nickname
- Roles

The embed colour should match the colour of their most senior role to be consistent with the quote embed.

**Comment by shyguy2601** [comment]
@LamboCreeper Assign me UWU

**Comment by BlackBearFTW** [comment]
@shyguy2601 do you still want to do this? Otherwise ill do it :)
