### ISSUE TITLE
Log Messages Which Are Bulked Deleted

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#131]
**As a** moderator
**I want to** be able to see messages which are deleted in bulk
**So that I** can see what the Anti Spam Bot deleted

--- 

**Event Trigger:** `messageDeleteBulk`

For each message returned in the collection, an embed should be sent to the logs channel. This logic should be very similar the `messageDelete` logic.

**Comment by shyguy2601** [comment]
@LamboCreeper do you just want it to say how many messages were deleted?

**Comment by LamboCreeper** [comment]
> @LamboCreeper do you just want it to say how many messages were deleted?

No, this should treat each message as it's own individual event.
