### ISSUE TITLE
Ghostping reply doesn't show original message author

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#133]
**Problem:** Currently the bot does detect when a reply was deleted that pinged the original message author, but the embed doesn't show that pinged user. Which would be useful information.

![reply](https://user-images.githubusercontent.com/62018777/99885719-46f1b080-2c37-11eb-9033-02a95fde35f7.JPG)

**Solution:** Add an if statement to check if the message was a reply, then add an extra field to the embed, that would look like:
**Replied To:**
@mention

**Optional:** Also show the content of the message that was replied to.

**Comment by BlackBearFTW** [comment]
so I just asked on the official discord.js server how you could detect if a message was a reply and got this answer:

> :sparkles: Discord.js will support inline replies in v13, replacing Message#reply with the new functionality.
If you'd like to try out the feature ahead of time (in a server with it enabled), please install and test this PR: https://github.com/discordjs/discord.js/pull/4874
You can e.g. use NPM to do this: npm i monbrey/discord.js#inline-replies (this requires git to be added to PATH)

**Comment by monbrey** [comment]
v12 can already check if a message was a reply using `Message#reference` as replies use the same property as crossposts which was already supported.

**Comment by BlackBearFTW** [comment]
> V13 implements the inline reply functionality, both for receiving and sending messages.

Oh someone said this when I asked about it
but it does indeed look like this would already be possible https://discord.js.org/#/docs/main/master/class/Message?scrollTo=reference
