### ISSUE TITLE
A custom pinning system.

### ISSUE THREAD

**Issue by Salint** [codesupport/discord-bot#137]
Since Discord has a limit of 50 pins per channel. I thought about making a custom pinning system where you'd be able to pin a message using it's ID, and a command to take a look at the pins, maybe giving the message link to "jump" to the message.

**Comment by ajsaraujo** [comment]
That would require the App to have some sort of state, so we could store the pinned messages' ids. We've been avoiding these kinds of features for now, since the bot is intended to be stateless. Any opinions @LamboCreeper?

**Comment by Salint** [comment]
> That would require the App to have some sort of state, so we could store the pinned messages' ids. We've been avoiding these kinds of features for now, since the bot is intended to be stateless. Any opinions @LamboCreeper?

By "state", do you mean a database or some way to store data?

**Comment by ajsaraujo** [comment]
Yes, exactly! Currently we don't have any database for the bot. We can't store it in a file either because it doesn't work out well in Heroku.

**Comment by Salint** [comment]
> Yes, exactly! Currently we don't have any database for the bot. We can't store it in a file either because it doesn't work out well in Heroku.

Sad. There will be a need sooner or later to use one. For example: Profiles, this pinning system, and a lot of other stuff.
