### ISSUE TITLE
Roleinfo command. 

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#157]
Would a command that gives you more information about a role be handy, for contributor and verified role (and others)? 

![Screenshot_20210322-134547.jpg](https://user-images.githubusercontent.com/62018777/111991987-33872100-8b15-11eb-8c7f-051e106245fc.jpg)

**Comment by LamboCreeper** [comment]
This isn't a big enough issue for us to worry about, closing.
