### ISSUE TITLE
"codeblocks" doesn't trigger the codeblock command

### ISSUE THREAD

**Issue by ajsaraujo** [codesupport/discord-bot#17]
Sometimes you want to trigger the codeblock command, so you enter `codeblocks`. Nothing happens. Then you try `codeblock` and it works. It would be nice if both `codeblock` and `codeblocks` triggered this command.

**Comment by LamboCreeper** [comment]
I think we should take this and add `alias` support to the `Command` abstract rather then just supporting it for this command. Great suggestion!
