### ISSUE TITLE
Bypass Ghostping for moderator deletes 

### ISSUE THREAD

**Issue by Bas-Sarrechia** [codesupport/discord-bot#181]
When a moderator deletes a message, no ghost ping message should be generated. Currently when a moderator removes a message, the ghost ping will trigger. Messages deleted by a mod generally get deleted with reason.

**Comment by BlackBearFTW** [comment]
I get where this is coming from, but what about the people that got pinged? The whole system was build to detect ghost pings.

If you have a message with a bunch of mentions and that needs to be deleted for whatever reason, all those mentioned users won't see why and where they got pinged. Resolving in someone being ghost pinged.

I get that moderators only remove message if it has some sort of inappropriate content and that the ghost ping then shouldn't show the message anymore, but maybe we can come up with a different solution?

For example we could still show the ghost ping, but maybe it just says the users who got pinged and not the other content, or add some sort of "Removed by moderator" behind it.

![image](https://user-images.githubusercontent.com/62018777/121487684-9bd9f600-c9d2-11eb-843e-eaf1daa9cb5b.png)

Its just a thought...

**Comment by Bas-Sarrechia** [comment]
No - the message should not be ghostping detected. It's more often a double delete has to happen because of x or y. to put this in perspective, I remove banter from #hiring-and-looking where a person is pinged concerning their post, I dont want to double remove a message to clean up the channel. The low amount of people that receive a ghostping is something that will have to deal with it then which is not problematic. - to further this perspective, in these situations I already double delete, there is zero complain as thus far.

**Comment by theboxmage** [comment]
This feature is only possible through using the audit logs. The message delete event only contains a Boolean value for if the message is deleted or not.

The audit logs are historically touch and go, and are not guaranteed to be present for the current delete. Unless someone wants to try tackling this with an attempt to stall for the update, I'm considering this not possible with the current implementation of the discord bot API.

**Comment by Bas-Sarrechia** [comment]
seems like the technical limitations prevent this from being an actual good feature unfortunate.
https://discordjs.guide/popular-topics/audit-logs.html#some-quick-background
