### ISSUE TITLE
flex command

### ISSUE THREAD

**Issue by Bas-Sarrechia** [codesupport/discord-bot#182]
create a command that provides the following information

Some recommended resources to learn flexbox include:
• MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout
• Flexbox.io - https://flexbox.io/
• Flexbox Froggy - https://flexboxfroggy.com/ (Basic gamified tutorial)
• Flexbox Zombies - https://geddski.teachable.com/p/flexbox-zombies(More in depth gamified tutorial)
• https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by LamboCreeper** [comment]
I would rather update the `?resources` command to return a link to the Resources page on the website with a search query rather than category such as https://codesupport.dev/resources?search=flex

This means that people may check out parts of the website, a platform I would like to grow.

**Comment by Bas-Sarrechia** [comment]
agreed - you can add a link at the end of the command to reference back to the website. Main functionality here is to support a verified member that often repeats this same static response back to people. Enhancing it with the website can lure people in to the website without forcing people to go to the website. - win win

**Comment by LamboCreeper** [comment]
Okay, cool then I propose we change the current implementation of the resources command:

**Usage:** `?resources <query>`

If the `<query>` is a valid category in the Resources API it pulls in the first three resources of that query with a link to the website (`codesupport.dev/resources?category=<query>`) else it will get the first matches based on a given query and return that link (`codesupport.dev/resources?search=<query>`). The embed could look as follows:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/12111454/121779198-654ad980-cb92-11eb-94a6-ebed2aa214ab.png">

**Comment by Bas-Sarrechia** [comment]
I would consider this a different functionality (story).
The resource command update looks good like that. In contrast, this is a relink to sources, the flex command I've advocated for, is meant to instantly provide information rather than it being a click away - these suggestions generally get given by people who explain who explain what flex is to new people (mainly mathais), and does not include the CS relink. by putting these resourced behind a secondary click, it'll lower the CTR (click through rate), while providing direct answers in discord, can provide incentive to check out the other resources.

**Comment by LamboCreeper** [comment]
Could you give me an example of the command usage and response please, I'm struggling to understand the differences?

**Comment by Bas-Sarrechia** [comment]
Actor A : Hey can anyone help me with positioning my html, i want element A to be placed at position B
Actor B : The best way to get to that solution would be to use flexbox, flexbox is a modern solution to posiitoning elements.
Actor A : Can you give me an example? I got a hard time understanding this, I've heard people talk about flexbox though
Actor B : Sure!
Actor B : ?flex
Bot : responds
Actor B : check out the links, they should help you, if you have any questions please feel free to reach out
Actor C : How can i make my discord bot say something?
Actor B : #javascript


effective response from the bot: 

Some recommended resources to learn flexbox include:
• MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout
• Flexbox.io - https://flexbox.io/
• Flexbox Froggy - https://flexboxfroggy.com/ (Basic gamified tutorial)
• Flexbox Zombies - https://geddski.teachable.com/p/flexbox-zombies(More in depth gamified tutorial)
• https://css-tricks.com/snippets/css/a-guide-to-flexbox/

To find more tips and tricks on javascript, check out [codesupport resource  website link]



------------------------

other direct examples:
https://discord.com/channels/240880736851329024/240883828103708683/855492360040480809
https://discord.com/channels/240880736851329024/240883828103708683/854084693380956180
https://discord.com/channels/240880736851329024/240883828103708683/849568258020868106
https://discord.com/channels/240880736851329024/240883828103708683/847879683614048326

**Comment by Bas-Sarrechia** [comment]
ps. This would make the help action primary over the advertising click through action, which in my opinion should be primary.

**Comment by BlackBearFTW** [comment]
I agree with iffy, but then what about other (css) resources like css-grid, do we just not add those because they are used less?

Wouldn't it be smarter just to use the can I use command instead, since that also provides information (but not resources, so maybe not a good solution after all)

And with the resources command it indeed doesn't give a detailed description about flexbox itself, just about the websites

What if we just have an faq channel? Which answers all the common questions,
From what is verified role to what is flexbox.

And any other common question.

**Comment by Bas-Sarrechia** [comment]
`I agree with iffy, but then what about other (css) resources like css-grid, do we just not add those because they are used less?`
 css grid is indeed not used as often, flex is specific since its a reoccuring topic and generally the main solution to most layout issues.

`Wouldn't it be smarter just to use the can I use command instead, since that also provides information (but not resources, so maybe not a good solution after all)`
unrelated

`And with the resources command it indeed doesn't give a detailed description about flexbox itself, just about the websites`
the point of adding an additional command, specific for the relative high volume this handles.

`What if we just have an faq channel? Which answers all the common questions,`
unrelated and not related to the discord bot. also likely a brood haven for a maze thats so informative noone will check it out because it's too much.

@LamboCreeper I'll close this feat for now, the fact you have this many questions concerning the feat tells me it's likely an over engineered solution for a small nice to have. There is the obv concern for 'if this is in the bot, why not this' which leads to a bloated set of features.
