### ISSUE TITLE
Remove Twitter Implementation

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#186]
The bot still has code and NPM packages relating to the Twitter functionality which we used to have. This can all now be removed.

**Comment by BlackBearFTW** [comment]
do you mean these resources?
```
import Twitter from "twitter";
import { TWITTER_ID } from "../config.json";
import TwitterStreamListener from "../interfaces/TwitterStreamListener";
class TwitterService {
```

I can remove those for you
