### ISSUE TITLE
bug/RaidDetection slow down warning messages

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#190]
### Overview
Please describe the bug below:
Currently the bot spams general full with warnings, I have a solution for this problem, by adding in a queue_counter that only sends the message every x amount of dealt with queues

### Expected Behaviour
Please describe how you expect this functionality to work:
It should slow down and not send that message as often

### Actual Behaviour
Please describe how this functionality is actually working:
As I said, general now gets spammed multiple times back to back.

**Comment by BlackBearFTW** [comment]
I already implemented this and also refactored the code, I plan on making a pr soon.

**Comment by LamboCreeper** [comment]
I always believed the issue to be with people not being removed from the queue, since the only way I could get the messages to stop spamming before was by restarting the Dyno. Do you know if this fixes that?

**Comment by BlackBearFTW** [comment]
Well the queue simply gets emptied out by setting it equal to []

I tried doing this.joinqueue.shift() but that broke a test.... So I would have to look into that

**Comment by theboxmage** [comment]
Can this issue be picked back up on a different approach? 

Checking the previous 10 or so messages for a bot post and skipping the Raid detection message would solve a lot of spamming. Would also still allow for the message to show up in chat enough for people to see it when they glance through general.

**Comment by LamboCreeper** [comment]
> Can this issue be picked back up on a different approach? 
> 
> 
> 
> Checking the previous 10 or so messages for a bot post and skipping the Raid detection message would solve a lot of spamming. Would also still allow for the message to show up in chat enough for people to see it when they glance through general.

This sounds good. Approving this solution.

**Comment by AlexChadwickP** [comment]
Make the bot stop raiding the server itself every time it detects a raid

**Comment by olivier-b-be** [comment]
> Make the bot stop raiding the server itself every time it detects a raid

Make the code so the bot stops raiding the server itself every time it detects a raid
