### ISSUE TITLE
A new feature which uses sandboxed API for executing user code on-the-fly

### ISSUE THREAD

**Issue by viabhinav** [codesupport/discord-bot#192]
### What Functionality Are You Suggesting?
Please describe the functionality below:
It will be a feature that will enable users to run code from many different languages in Discord itself, under a sandboxed API environment.
### Why Will This Benefit The Community?
Please explain why this functionality would benefit our community below:
This feature will greatly help helpers as they would be able to run the problematic code and see the error or output in detail on the fly without opening a compiler. If output is long or it is an error it will be dmed so they can fix it efficiently. Very beneficial for small problems.

**Comment by LamboCreeper** [comment]
Closing as per Iffy’s [comment](https://github.com/codesupport/discord-bot/pull/193#issuecomment-875773062).
