### ISSUE TITLE
Necessity of detecting ghost pinging bots

### ISSUE THREAD

**Issue by ChrisCh7** [codesupport/discord-bot#196]
Currently, ghost pinging by deleting a message mentioning a bot (only bot or author + bot) is detected.
Deleting a reply (ping = on) to a bot is detected as well.

Is that the intended behavior? If not, I'd like to fix it.

**Comment by BlackBearFTW** [comment]
Might I also suggest refactoring that class, it looks like a mess, should probably break up the reply and normal ghost ping functionality into separate methods. 

Also, I don't think its the intended behaviour, but it didn't bother anyone, that is why it wasn't changed, but that is just a guess...

**Comment by ChrisCh7** [comment]
I tried refactoring it, but the method for the reply ended up being basically the same as the original method, due to the various null/undefined checks.
So I'd prefer to keep this issue/PR strictly about the functionality.

**Comment by theboxmage** [comment]
Just to confirm, you're only talking about mentions to @CodeSupport? Or are you referring to when you reply to a user with a bot command. 

Either way, this isn't a scenario we've had significant issues with before, posting an example for clarity would be useful.

**Comment by BlackBearFTW** [comment]
> Just to confirm, you're only talking about mentions to @CodeSupport? Or are you referring to when you reply to a user with a bot command. 
> 
> Either way, this isn't a scenario we've had significant issues with before, posting an example for clarity would be useful.

He is talking about that first one, when you mention a bot (either normally or through a reply) and then delete the message, it still gets detected, even if you just pinged the bot.

**Comment by ChrisCh7** [comment]
Not just the CodeSupport bot, any bot.

Example 1, deleted message:
hey @Chris7 @CodeSupport

Example 2, deleted message:
hey @CodeSupport @DankMemer

Example 3, deleted reply to @CodeSupport (or any bot):
hey

**Comment by LamboCreeper** [comment]
Thank you for raising this, it would be great if you were willing to fix this for us!
