### ISSUE TITLE
Hiring-and-looking custom cooldown against spam posts

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#198]
### What Functionality Are You Suggesting?
Please describe the functionality below:
Add a handler that allows users to only post in hiring-and-looking every x amount of days.

### Why Will This Benefit The Community?
Please explain why this functionality would benefit our community below:
This will stop spam posts and it will also make life easier for the moderators.

![Screenshot_20210729-223037.jpg](https://user-images.githubusercontent.com/62018777/127566968-cc0c4037-1701-4faa-997b-5edd1ceb4efc.jpg)

**Comment by LamboCreeper** [comment]
Closing due to lack of approval. Our hiring/looking process has also changed from when this issue was raised.
