### ISSUE TITLE
Advertisement blocker

### ISSUE THREAD

**Issue by AtrumAmantus** [codesupport/discord-bot#204]
### What Functionality Are You Suggesting?
Please describe the functionality below:

Feature to detect and respond to a limited scope of suspected advertisements.
 - Feature will be limited to members who have joined within X (configurable) hours with the `Member` role.
   - Messages will be tracked in-memory only.
   - Tracked user messages will be erased after user has stayed for longer than X (configurable) hours.
 - Feature will kick users who post the same message in N (configurable) channels.
 - Feature will delete only the messages from the user that triggered the advertisement detection.

### Why Will This Benefit The Community?
Please explain why this functionality would benefit our community below:

There have been an increase in nitro advertisements being spammed in multiple channels.  This feature will allow these messages to be quickly cleaned up and dealt with when moderators are not available, allowing them to add additional bans manually at a later point via the logged messages.

**Comment by LamboCreeper** [comment]
Closing due to lack of approval. Discord now has built in spam detection.
