### ISSUE TITLE
Ghost Ping not detected on message edit

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#242]
### Overview
Please describe the bug below:
When you edit a message that contains a ping and remove the mention, it doesn't trigger ghost ping.
### Expected Behaviour
Please descripe how you expect this functionaltiy to work:
This should show the ghost ping embed.
### Actual Behaviour
Please describe how this functionality is actually working:
The user still gets the ping, but since the message was edited, it doesn't show where they were pinged.

**Comment by olivier-b-be** [comment]
What's the preferred way in your eyes to change this? The EventHandler only takes in one argument in the constructor which is specifically for the delete event, I'm sure the update also needs some slightly different code but considering the name currently is `GhostPingHandler` it seems like it has everything to do with any form of ghost pings

**Comment by theboxmage** [comment]
Messages have a mentions object, just check to see if all the elements in the old message are the same as the new.

**Comment by theboxmage** [comment]
Now that I have a real keyboard. 
I'm advocating for either a new handler or an update to the LogUpdateMessageHandler. A new GhostPingUpdateHandler (name pending) is more verbose and probably fits better in our design pattern. This would sit on the Message Update event, which gives two params when it resolves.

The other, lazier, option is to jam it into the existing LogUpdateMessageHandler. 

I'd be willing to look at either option, but a new handler feels like the safer better choice.

**Comment by olivier-b-be** [comment]
GhostPingUpdateHandler seems good to me, do I rename the current GhostPingHandler to GhostPingDeleteHandler?

**Comment by theboxmage** [comment]
Sure, that sounds like a reasonable change to make.
