### ISSUE TITLE
Integrate Piston Sandbox API

### ISSUE THREAD

**Issue by BlackBearFTW** [codesupport/discord-bot#249]
### What Functionality Are You Suggesting?
https://github.com/dthree/node-piston
The Piston API allows us to run code in a sandboxed environment. I suggest adding a command 

/run py
```py
print("Hello World");
```

Which would return

Codeblock Result (ran in 2ms)
```py
Hello World
```

### Why Will This Benefit The Community?
It would allow members to run small codesnippets, instead of making a repl.

It would also allow members to test out certain snippets for quirks

/run js
```js
[] == []
```

Codeblock Result (ran in 5ms)
```js
false
```

**Comment by BlackBearFTW** [comment]
Another solution could be implementing it into a modal

**Comment by LamboCreeper** [comment]
Closing due to lack of approval.
