### ISSUE TITLE
Moderators should be exempt from file upload restrictions in the mods channel

### ISSUE THREAD

**Issue by saramaebee** [codesupport/discord-bot#260]
### Overview
When moderators are chatting in the #mods channel, they are blocked from uploading files outside of the accepted extensions. Occasionally we have good reasons for uploading PDFs or other types of documents. 

### Expected Behaviour
Moderators are exempted from file upload restrictions in the #mods channel

### Actual Behaviour
Please descripbe how this fucntionality is actually working:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/34497797/187590737-26b09c28-6f4f-4e5e-9307-2f03a296fc92.png">

**Comment by LamboCreeper** [comment]
Should the exception be based on role, channel or both?

**Comment by theboxmage** [comment]
I'd advocate for channel. We had the same request for Verified members with #180 and it closed without implementation. If it's truly for just moderation activities, a channel list might be appropriate. 

i.e. #mods, #verified, and #member-notes

**Comment by saramaebee** [comment]
yea, i can see an argument for it being scoped to roles as well, but I don't think any of us are really the type to send PDFs when teaching people something. we'd likely just link to the pdf online

**Comment by LamboCreeper** [comment]
Cool, let's leave it at channels for now. Makes sense.
