### ISSUE TITLE
Removing self-pings doesn't trigger a ghost ping alert

### ISSUE THREAD

**Issue by hexathe6** [codesupport/discord-bot#282]
### Overview
Removing a message containing a self-ping doesn't trigger a ghost ping alert.
Editing a self-ping out of a message also doesn't trigger an alert.

### Expected Behaviour
Removing a message containing a self-ping triggers a ghost ping alert, as does editing out the ping.
(this may not be desirable, but it's at least consistent with the rest of the hassle that ghost pings bring)

### Actual Behaviour
Neither method of removing the self-ping triggers a ghost ping alert. (see §Overview)

**Comment by theboxmage** [comment]
This is not a bug, it is intended behavior in both the update and delete handlers.
