### ISSUE TITLE
NPM Command

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#29]
Get a link to an NPM package.

Command Usage: `?npm <package>`

If a package is not supplied, return an error stating the correct usage (similar to the `?rule` command). If a package is supplied, perform a GET request: if 200 is returned send the link as the package is valid, if not state that a package of the supplied name could not be found.

This command should function identically to the one in the old Discord bot (see [here](https://github.com/codesupport/old-discord-bot/blob/develop/commands/npm.js)).

**Comment by ajsaraujo** [comment]
I'm on it. 😎
