### ISSUE TITLE
Message Logs

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#30]
```
As a: Moderator
I want to: see message logs
So that: I can see if anything suspicious is being said
```

When a message is edited, it should be logged to the `#logs` channel (ID: `405068878151024640`) with the previous content, new content and author:
<img width="589" alt="message-updated" src="https://user-images.githubusercontent.com/12111454/83898852-68c1ae80-a74f-11ea-98d7-94e4b83a6eac.png">
This should be done in`LogMessageUpdateHandler`.

When a message is deleted, logged to the `#logs` channel (ID: `405068878151024640`) with the previous content and author. This should be done in`LogMessageDeleteHandler`.

**Comment by jacobgasser** [comment]
ok dw bby im on it
