### ISSUE TITLE
?search Does Not Support Subdomains

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#31]
If an InstantAnswer query result is from a website that uses a subdomain, the URL is cut short in the MessageEmbed. See below:
![Discord_2020-06-05 17-23-34@2x](https://user-images.githubusercontent.com/12111454/83900017-4df03980-a751-11ea-81d6-d889325d9ee9.png)

**Comment by ajsaraujo** [comment]
I'll take a look at it.
