### ISSUE TITLE
Enforce Codeblocks Over File Uploads

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#33]
```
As a: Member
I want to: Be told to use a codeblock over a file upload
So that: People do not have to download my code
```

@AtrumAmantus suggested to me that it would be a good idea to detect file uploads and tell users to send their code as codeblock rather than a file upload.

I think the simplest way to do this would be by just allowing uploads of:
- `.jpg`
- `.jpeg`
- `.png`
- `.gif`
- `.mp4`

If we detect they are uploading a file which does not match one of those extensions the bot should say:
> @UserWhoUploadedTheFile Please use codeblocks over uploading code files. Type ?codeblock for more information.

The supported file extensions should be stored in the `config.json` as an array of strings called `SUPPORTED_FILE_UPLOADS`.

This should be done in `CodeblocksOverFileUploadsHandler`.

**Comment by theboxmage** [comment]
Looking into this, running with the assumption of deleting file uploads.
