### ISSUE TITLE
Persistent Muting

### ISSUE THREAD

**Issue by jacobgasser** [codesupport/discord-bot#37]
Currently, when a user leaves the server with the muted role the muted role goes with them. They are able to rejoin and wreak havoc once again (like i did). 

There should be a way so that the mute persists through kicking or the muted user leaving and rejoining.

**Comment by ajsaraujo** [comment]
How would one go about implementing that? Is the role data persisted anywhere?

**Comment by bluedaze** [comment]
I think a good way to go about ensuring that someone stays muted is that the bot will mute someone who left upon rejoining.

**Comment by LamboCreeper** [comment]
Thanks for raising this issue, that's actually a good point that I've never thought of. This also applies for any roles, not just mutes. For example, if a Supporter left and rejoined they'd no longer have that role.

> How would one go about implementing that? Is the role data persisted anywhere?

Currently, no. I don't really want to store user data (as far as I'm aware Discord is iffy about people doing it. Although, I suppose storing an array of role IDs against a user ID is no trouble. I think this is something to discuss over on Discord.

> I think a good way to go about ensuring that someone stays muted is that the bot will mute someone who left upon rejoining.

Yeah, that's probably the best way about doing it. The problem is just how we know whether or not they had these roles previously.

**Comment by bluedaze** [comment]
Would be a good reason to keep a moderation log. Just stream moderation events into a channel. When someone is muted unless the moderation log shows that they were explicitly unmuted they are automatically muted again upon rejoining.

**Comment by LamboCreeper** [comment]
> Would be a good reason to keep a moderation log. Just stream moderation events into a channel. When someone is muted unless the moderation log shows that they were explicitly unmuted they are automatically muted again upon rejoining.

Yeah, so this is being added in #30 (although just for message editing and deleting). I'm not entirely sure what you mean by the last bit - are you suggesting we manually do it or not?

**Comment by bluedaze** [comment]
Okay, so from my understanding when someone is given the role that mutes users it should show in the audit log. So the role can be automatically reassigned again upon rejoining, unless the audit log shows that this role was removed. 

I created a temporary server to server as an example here:

https://i.imgur.com/2zk3mIU.png

As you can see I assigned the role to a user here, but then I had to assign it again after they left and they came back. However, if I remove a role from said user it shows that I have removed it.

So if you program the bot to keep track of audit events you can ensure that the roles remains consistent when rejoining. (Actually, this would probably be a good idea in general, tbh.) Therefore, if someone rejoins they are automatically muted upon rejoining, as the role is added to their account again.

**Comment by LamboCreeper** [comment]
> Okay, so from my understanding when someone is given the role that mutes users it should show in the audit log. So the role can be automatically reassigned again upon rejoining, unless the audit log shows that this role was removed.
> 
> I created a temporary server to server as an example here:
> 
> https://i.imgur.com/2zk3mIU.png
> 
> As you can see I assigned the role to a user here, but then I had to assign it again after they left and they came back. However, if I remove a role from said user it shows that I have removed it.
> 
> So if you program the bot to keep track of audit events you can ensure that the roles remains consistent when rejoining. (Actually, this would probably be a good idea in general, tbh.) Therefore, if someone rejoins they are automatically muted upon rejoining, as the role is added to their account again.

Great idea! As far as I recall working with the audit log is a pain - do they even save permanently? If you'd be interested in implementing this it'd be awesome.

**Comment by bluedaze** [comment]
I'm not at all familiar with typescript, but when I have time I will look it over.

**Comment by kaelon141** [comment]
What's the status on this issue? if it's still up for grabs this is something I'm willing to pick up.

As for what's discussed above, from a bit of research (read: google), it seems like the audit log does not save permanently and so it cannot really be used to keep track of a user's roles.

The best way to solve this would be by persisting the role data and updating it when members gain/lose roles. This can be done by either setting up a database or saving the role data in json files. I'm fine implementing either.

**Comment by LamboCreeper** [comment]
> What's the status on this issue? if it's still up for grabs this is something I'm willing to pick up.
> 
> 
> 
> As for what's discussed above, from a bit of research (read: google), it seems like the audit log does not save permanently and so it cannot really be used to keep track of a user's roles.
> 
> 
> 
> The best way to solve this would be by persisting the role data and updating it when members gain/lose roles. This can be done by either setting up a database or saving the role data in json files. I'm fine implementing either.

Thanks for the interest in this feature. I am not willing for us to save data (whether that be through a file on system or database).

I’m not sure how relevant this still is, since we do all our muting through a separate anti-spam bot which has this functionality.

**Comment by LamboCreeper** [comment]
This doesn't prove itself to be a big issue, closing.
