### ISSUE TITLE
Embed Colours

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#41]
We should take advantage of the ability to colourise embeds depending on their status:
- Successes should be green (`#35BC31`)
- Errors should be red (`#BC3131`)
- Anything else should be the CodeSupport Blue (`#1555B7`)

These should be stored in the `config.json` as:
```json
{
    "EMBED_COLOURS": {
        "SUCCESS": "#35BC31",
        "ERROR": "#BC3131",
        "DEFAULT": "#1555B7"
    }
}
```

Tests should also check the right embed colour is being sent if an embed and tested. **Do not compare the value to the one in the config** - these are not integration tests!

**Comment by ajsaraujo** [comment]
I'll take a look at this. :+1:
