### ISSUE TITLE
Stop Commands Being Run In #hiring-or-looking

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#43]
Commands should not be allowed to run in the #hiring-or-looking channel (ID: `328146607486795777`).

**Comment by ajsaraujo** [comment]
Can I take this? Where would this check happen? I thought of putting it in the CommandParserHandler.

**Comment by LamboCreeper** [comment]
> Can I take this? Where would this check happen? I thought of putting it in the CommandParserHandler.

Sounds good to me!
