### ISSUE TITLE
GitHub Command

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#58]
This should be similar to the SearchCommand and InstantAnswerService.

## GitHubService
Create a GitHubService singleton (just base it on any of the other services) with method `getRepository(user: string, repo: string)` that calls `https://api.github.com/repos/<user>/<repository>`.

## GitHubCommand
Command Usage: `?github <username>/<repository>`

If a parameter is not supplied, return an error stating the correct usage (similar to the ?npm command). If a parameter is supplied, perform a GET request: if 200 is returned send an embed with the repository information as the repository is valid, if not state that a repository of the supplied name could not be found.

The embed should contain:
- The repository name and who it's by in the title
- The description of the repository
- The primary language of the repository
- The number of open issues
- The number of open pull requests
- A button to view the repository on GitHub

_We could also add the number of forks and stars, but it might make the embed quite large._

**Comment by LamboCreeper** [comment]
@BananaCrazy just notified me that pull requests are not returned via that endpoint. You will have to create another method on the GitHubService - `getPullRequests(user: string, repo: string)` which calls `https://api.github.com/repos/<user>/<repository>/pulls`.

**Comment by BananaCrazy** [comment]
Will do (or try :D )
