### ISSUE TITLE
GitHub Issues Command

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#69]
Usage: `?issues <username>/<repository>`

```
As a: user
I want to: get a list of issues for a specific repository
So that I: can see them in Discord
```

This will require updating the `GitHubService` so that it has a new method, `getIssues()`, which returns an array of `GitHubIssue`s (this will require a new interface).

When executing the command, an embed should be sent with the 3 most recent issues:
![Example Embed](https://cdn.discordapp.com/attachments/720675405413089311/727599862178119830/unknown.png)

**Comment by BananaCrazy** [comment]
I can add it to the bot
