### ISSUE TITLE
Re-implement Twitter Service

### ISSUE THREAD

**Issue by LamboCreeper** [codesupport/discord-bot#91]
We removed the Twitter service temporarily in #85 to fix a bug where the bot crashed on deployment.

We need this feature added back, but obviously do not want it to crash the bot.

**Comment by shyguy2601** [comment]
@LamboCreeper could I get a bit more detail on this one please?

**Comment by LamboCreeper** [comment]
> @LamboCreeper could I get a bit more detail on this one please?

This feature is currently on hold until Twitter Streaming API becomes more easily accessible via a Node SDK again. Sorry, should have made more clear.

**Comment by LamboCreeper** [comment]
No longer required due to the use of Webhooks for this functionality.
