### ISSUE TITLE
Quote System improvements

### ISSUE THREAD

**Issue by ajsaraujo** [codesupport/discord-bot#97]
- Serialize URLs
- Display date and time as depicted [here](https://cdn.discordapp.com/attachments/720675405413089311/738315596927598632/unknown.png)
- Display which channel the message was sent in

**Comment by ajsaraujo** [comment]
@LamboCreeper, what did you mean by "Serialize URL"? I think I'll take a look at this issue later, but this isn't clear yet.

**Comment by LamboCreeper** [comment]
> @LamboCreeper, what did you mean by "Serialize URL"? I think I'll take a look at this issue later, but this isn't clear yet.

So currently users can type `[something](https://url.tld)` and it won't do anything, but once that message is quoted it becomes an actual clickable link as embeds support that.

**Comment by jacobgasser** [comment]
Does it delete the original link that is sent? I feel like it should either be deleted or some information should be removed from the embed

**Comment by LamboCreeper** [comment]
> Does it delete the original link that is sent? I feel like it should either be deleted or some information should be removed from the embed

I would rather the "called by" text was removed, but the link kept. I think it's more obvious that way who triggered it.
